monitor=,preferred,auto,1

exec-once = waybar

exec-once = hyprpaper

exec-once = kitty

input {
    kb_layout=latam
}

general {
    gaps_in=5
    gaps_out=10
}

bind=SUPER,Q,exec,kitty

bind=SUPER,R,exec,wofi --show drun