monitor=,preferred,auto,1

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprpaper
exec-once = waybar

$terminal = kitty
$menu = wofi --show drun

bind = SUPER, Return, exec, $terminal
bind = SUPER, D, exec, $menu
bind = SUPER, Q, killactive
bind = SUPER, M, exit

input {
    kb_layout = latam
}

general {
    gaps_in = 5
    gaps_out = 10
}